### ISSUE TITLE
Why do we mention 9.7.1?

### ISSUE THREAD

**Issue by jdwnetapp** [NetAppDocs/ontap-tools-vmware-vsphere#47]
### Page URL

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html

### Page title

Migration of Windows SRM to SRM Appliance

### Summary

Why is step #1 version specific?  And this sentence is grammatically incorrect:

"1. Upgrading your existing ONTAP tools to the 9.7.1 release."

A better sentence would be:

"1. Upgrade your existing ONTAP Tools Appliance to the latest release"

Additionally, why does the URL for this "Upgrade to the latest release of ONTAP tools" have 9_8 in it?

https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-jani** [comment]
@jdwnetapp 
Thank you for contacting us with your feedback. After your inputs are researched internally, we will determine how best to address it and update the content at the earliest.

Regards,
Jani

**Comment by netapp-jani** [comment]
@jdwnetapp, the [Migration of Windows SRM to SRM Appliance](https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/protect/concept_migration_of_disaster_recovery_setup_from_windows_to_appliance.html) page is updated to reflect correct information. 
The URL: https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/deploy/task_upgrade_to_the_9_8_ontap_tools_for_vmware_vsphere.html has 9.8 in it because it picks up the file name. The file was first created for 9.8 release. This can be ignored. 
Thank you for your feedback.
